"""environment prop added for api_key

Revision ID: 04a5e89ecc2a
Revises: 070b3412a46d
Create Date: 2026-08-31 11:14:36.438366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a5e89ecc2a'
down_revision: Union[str, Sequence[str], None] = '070b3412a46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('environment', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'environment')
    # ### end Alembic commands ###
