"""unique product base per tenant

Revision ID: 2483bf574036
Revises: c43c9fb1c5a5
Create Date: 2026-08-28 10:49:38.585143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2483bf574036'
down_revision: Union[str, Sequence[str], None] = 'c43c9fb1c5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_bases_tenant_id', 'product_bases', ['tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_bases_tenant_id', 'product_bases', type_='unique')
    # ### end Alembic commands ###
